### ISSUE TITLE
multiple_inputs.ipynb redundant features bug

### ISSUE THREAD

**Issue by adpala** [janclemenslab/glm_utils#9]
In the last example of the demo, sometimes (not always) filters from LinearRegression are returned out of scale, despite the model performance being 1.0.

Lasso model behaves normal, which means the inputs shouldn't be the problem, and the model score is still 1, which suggests the model is not the problem.

Plotting or filter reconstruction are the best candidates, but nothing looks suspicious.

Repeated saves and runs, eventually make the plot resemble what we expect, but filters do not match perfectly to the original filters, and redundant feature is nonzero. However model performance is always 1.

**Comment by postpop** [comment]
Switched to Lasso for all fits and edited the text.
